//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StormTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_table
    {
        public Invoice_table()
        {
            this.Purchase_Table = new HashSet<Purchase_Table>();
        }
    
        public string Number { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public double Total { get; set; }
    
        public virtual ICollection<Purchase_Table> Purchase_Table { get; set; }
    }
}
