//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StormTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_table
    {
        public Item_table()
        {
            this.Purchase_Table = new HashSet<Purchase_Table>();
        }
    
        public int ID { get; set; }
        public int Supplier_ID { get; set; }
        public string Description { get; set; }
    
        public virtual Supplier_table Supplier_table { get; set; }
        public virtual ICollection<Purchase_Table> Purchase_Table { get; set; }
    }
}
