//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StormTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Table
    {
        public Purchase_Table()
        {
            this.Invoice_table = new HashSet<Invoice_table>();
        }
    
        public int Order_Number { get; set; }
        public int Item_ID { get; set; }
    
        public virtual ICollection<Invoice_table> Invoice_table { get; set; }
        public virtual Item_table Item_table { get; set; }
    }
}
